# Generated by Django 5.2.8 on 2025-11-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название языка')),
                ('code', models.CharField(max_length=10, verbose_name='Код языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=200, verbose_name='Слово на иностранном языке')),
                ('translation', models.CharField(max_length=200, verbose_name='Перевод')),
                ('example_sentence', models.TextField(blank=True, verbose_name='Пример использования')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('language_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_from', to='vocabulary.language', verbose_name='Исходный язык')),
                ('language_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_to', to='vocabulary.language', verbose_name='Язык перевода')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
